version: "3.1"
secrets:                        # top level secrets block
  gwq5210.com.key:
    file: certs/gwq5210.com/gwq5210.com.key
  gwq5210.com.crt:
    file: certs/gwq5210.com/gwq5210.com.crt
  ca.crt:
    file: certs/ca/ca.crt
  mysql_root_password:
    file: mysql/conf/mysql_root_password.txt
  v2ray_uuid:
    file: v2ray/conf/v2ray_uuid.txt
  scrapyd_username:
    file: scrapyd/conf/scrapyd_username.txt
  scrapyd_password:
    file: scrapyd/conf/scrapyd_password.txt

services:
  gwq5210.nginx:
    # image: gwq5210/nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: gwq5210.nginx
    restart: always
    secrets:
     - gwq5210.com.key
     - gwq5210.com.crt
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html:/var/www/gwq5210.com/html
      - /var/log/nginx:/var/log/nginx
    # network_mode: "host"
    ports:  # host模式这个配置失效
      - "80:80"
      - "443:443"
      - "6800:6800"  # scrapyd
      - "6010:6010"  # tank
      - "8888:8888"  # phpmyadmin
      - "9090:9090"  # filebrowser
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - gwq5210.tank
      - gwq5210.php
      - gwq5210.phpmyadmin
      - gwq5210.v2ray
      - gwq5210.filebrowser
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.2'
          memory: 128M

  gwq5210.mysql:
    # image: gwq5210/mysql
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    restart: always
    container_name: gwq5210.mysql  # 容器名
    secrets:
     - mysql_root_password
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - /var/log/mysql:/var/log/mysql
      - /var/lib/mysql:/var/lib/mysql  # 挂载目录，持久化存储
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password  # 使用docker secret设置root用户的密码
      MYSQL_DATABASE: "tank"

  gwq5210.tank:
    # image: gwq5210/tank
    build:
      context: .
      dockerfile: ./tank/Dockerfile
    restart: always
    container_name: gwq5210.tank
    volumes:
      - /usr/share/tank/matter:/data/build/matter
      - /etc/tank/:/data/build/conf
      - /var/log/tank:/data/build/log
    # ports:
    #   - "127.0.0.1:6011:6010"
    depends_on:
      - gwq5210.mysql
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.2'
          memory: 128M

  gwq5210.php:
    # image: gwq5210/php
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: gwq5210.php
    restart: always
    # ports:
    #   - "127.0.0.1:9000:9000"
    volumes:
      - ./nginx/html:/var/www/gwq5210.com/html
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 128M

  gwq5210.phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gwq5210.phpmyadmin
    # ports:
    #   - "127.0.0.1:8889:80"
    environment:
      TZ: Asia/Shanghai
      PMA_HOST: gwq5210.com
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - gwq5210.mysql
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 128M

  gwq5210.v2ray:
    # image: gwq5210/v2ray
    build:
      context: .
      dockerfile: ./v2ray/Dockerfile
    restart: always
    container_name: gwq5210.v2ray  # 容器名
    secrets:
     - v2ray_uuid
    volumes:
      - ./v2ray/conf/config.json:/etc/v2ray/config.json
      - /var/log/v2ray:/var/log/v2ray
    # ports:
    #   - "127.0.0.1:10000:10000"
    environment:
      TZ: Asia/Shanghai
      V2RAY_UUID_FILE: /run/secrets/v2ray_uuid
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 128M

  gwq5210.filebrowser:
    # image: gwq5210/filebrowser
    build:
      context: .
      dockerfile: ./filebrowser/Dockerfile
    restart: always
    container_name: gwq5210.filebrowser  # 容器名
    volumes:
      - /usr/share/filebrowser/data:/srv
      - /etc/filebrowser:/etc/filebrowser
      - ./filebrowser/conf/filebrowser.json:/.filebrowser.json
    # ports:
    #   - "127.0.0.1:9091:80"
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 128M

  gwq5210.scrapyd:
    # image: gwq5210/scrapyd
    build:
      context: .
      dockerfile: ./scrapyd/Dockerfile
    container_name: gwq5210.scrapyd  # 容器名
    # ports:
    #   - "127.0.0.1:6801:6800"
    volumes:
      - ./scrapyd/conf:/etc/scrapyd
      - /usr/share/scrapyd:/usr/share/scrapyd
      - /var/log/scrapyd:/var/log/scrapyd
    restart: always
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 128M

  gwq5210.mirai:
    # image: gwq5210/mirai:latest
    build:
      context: .
      dockerfile: ./mirai/Dockerfile
    restart: always
    container_name: gwq5210.mirai  # 容器名
    volumes:
      - /usr/share/mirai/config:/root/mirai/config
      - /usr/share/mirai/plugins:/root/mirai/plugins
      - /usr/share/mirai/logs:/root/mirai/logs
      - /usr/share/mirai/bots:/root/mirai/bots
      - ./mirai/conf/Console/AutoLogin.yml:/root/mirai/config/Console/AutoLogin.yml
      - ./mirai/conf/net.mamoe.mirai-api-http/setting.yml:/root/mirai/config/net.mamoe.mirai-api-http/setting.yml
    # ports: 
    #   - "127.0.0.1:8080:8080"
    environment:
      TZ: Asia/Shanghai
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.1'
    #       memory: 128M
    #     reservations:
    #       cpus: '0.1'
    #       memory: 128M

  gwq5210.elasticsearch:
    # image: gwq5210/elasticsearch:latest
    build:
      context: .
      dockerfile: ./elasticsearch/Dockerfile
    container_name: gwq5210.elasticsearch
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - ELASTIC_PASSWORD=elastic
    secrets:
      - source: gwq5210.com.crt
        target: $ES_CERTS_DIR/gwq5210.com.crt
      - source: gwq5210.com.key
        target: $ES_CERTS_DIR/gwq5210.com.key
      - source: ca.crt
        target: $ES_CERTS_DIR/ca.crt
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      # - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: curl --cacert $ES_CERTS_DIR/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  gwq5210.kibana:
    # image: gwq5210/kibana
    build:
      context: .
      dockerfile: ./kibana/Dockerfile
    container_name: gwq5210.kibana
    restart: always
    depends_on:
      gwq5210.elasticsearch:
        condition: service_healthy
    ports:
      - 5601:5601
    environment:
      TZ: Asia/Shanghai
      SERVERNAME: localhost
      ELASTICSEARCH_URL: https://gwq5210.com:9200
      ELASTICSEARCH_HOSTS: https://gwq5210.com:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: elastic
    secrets:
      - source: gwq5210.com.crt
        target: $KIBANA_CERTS_DIR/gwq5210.com.crt
      - source: gwq5210.com.key
        target: $KIBANA_CERTS_DIR/gwq5210.com.key
      - source: ca.crt
        target: $KIBANA_CERTS_DIR/ca.crt
    volumes:
      - ./kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    healthcheck:
      test: curl --cacert $KIBANA_CERTS_DIR/ca.crt -k https://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  setup_certs:
    # image: gwq5210/elasticsearch:latest
    build:
      context: .
      dockerfile: ./elasticsearch/Dockerfile
    restart: on-failure
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch/setup_certs.sh:/usr/share/elasticsearch/setup_certs.sh
    working_dir: /usr/share/elasticsearch
    command:
      - /bin/sh
      - -c
      - |
        sh setup_certs.sh
        # echo "Waiting for Elasticsearch availability";
        # until curl -v --cacert config/certs/ca/ca.crt https://gwq5210.elasticsearch:9200 | grep -q "missing authentication credentials"; do sleep 5; done;
        # echo "Setting kibana_system password";
        # until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/gwq5210.com/gwq5210.com.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120