version: "3.1"

secrets:
  # top level secrets block
  gwq5210.com.key:
    file: secrets/gwq5210.com.key
  gwq5210.com.crt:
    file: secrets/gwq5210.com.crt
  ca.crt:
    file: certs/ca/ca.crt
  mysql_root_password.txt:
    file: secrets/mysql_root_password.txt
  v2ray_uuid.txt:
    file: secrets/v2ray_uuid.txt
  scrapyd_username.txt:
    file: secrets/scrapyd_username.txt
  scrapyd_password.txt:
    file: secrets/scrapyd_password.txt
  elasticsearch_bootstrap_password.txt:
    file: secrets/elasticsearch_bootstrap_password.txt
  elasticsearch_keystore_password.txt:
    file: secrets/elasticsearch_keystore_password.txt
  napcat_webui_token.txt:
    file: secrets/napcat_webui_token.txt

services:
  gwq5210_nginx:
    image: gwq5210/nginx:latest
    container_name: gwq5210_nginx
    secrets:
      - gwq5210.com.key
      - gwq5210.com.crt
    volumes:
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/var/www/gwq5210.com/html
      - ${DOCKER_SITE_LOGS_DIR}/nginx:/var/log/nginx
    ports:
      # host模式这个配置失效
      - "80:80"
      - "443:443"
      - "9445:9445"
      - "9447:9447"
      - "19443:19443"
      - "19445:19445"
      - "19447:19447"
      - "19449:19449"
      - "22333:22333"
    depends_on:
      - gwq5210_scrapyd
      - gwq5210_elasticsearch
      - gwq5210_kibana
      - gwq5210_v2ray
      - gwq5210_phpmyadmin
      - gwq5210_php
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 2048M

  gwq5210_mysql:
    image: gwq5210/mysql:latest
    container_name: gwq5210_mysql # 容器名
    secrets:
      - mysql_root_password.txt
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ${DOCKER_SITE_LOGS_DIR}/mysql:/var/log/mysql
      - ${DOCKER_SITE_KEY_DATA_DIR}/mysql:/var/lib/mysql # 挂载目录，持久化存储
      - ${DOCKER_SITE_BACKUP_DIR}/mysql:/usr/share/mysql/backup
      - ./mysql/mysql_backup.sh:/usr/local/bin/mysql_backup.sh
    ports:
      - "3306:3306"
      - "33060:33060"
      - "33061:33061"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password.txt # 使用docker secret设置root用户的密码
      MYSQL_DATABASE: "tank"
    deploy:
      resources:
        limits:
          memory: 4096M

  gwq5210_php:
    image: gwq5210/php:latest
    container_name: gwq5210_php
    volumes:
      - ./nginx/html:/var/www/gwq5210.com/html
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 2048M

  gwq5210_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: gwq5210_phpmyadmin
    environment:
      TZ: Asia/Shanghai
      PMA_ABSOLUTE_URI: https://phpmyadmin.gwq5210.com
      PMA_HOST: gwq5210.com
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - gwq5210_mysql
    deploy:
      resources:
        limits:
          memory: 2048M

  gwq5210_v2ray:
    image: gwq5210/v2ray:latest
    container_name: gwq5210_v2ray # 容器名
    secrets:
      - v2ray_uuid.txt
    volumes:
      - ./v2ray/conf/config.json:/etc/v2ray/config.json
      - ${DOCKER_SITE_LOGS_DIR}/v2ray:/var/log/v2ray
    environment:
      TZ: Asia/Shanghai
      V2RAY_UUID_FILE: /run/secrets/v2ray_uuid.txt
    deploy:
      resources:
        limits:
          memory: 2048M

  gwq5210_scrapyd:
    image: gwq5210/scrapyd:latest
    container_name: gwq5210_scrapyd # 容器名
    volumes:
      - ./scrapyd/conf:/etc/scrapyd
      - ${DOCKER_SITE_LOGS_DIR}/scrapyd:/var/log/scrapyd
      - ${DOCKER_SITE_DATA_DIR}/scrapyd:/var/lib/scrapyd
      - ${DOCKER_SITE_DATA_DIR}/downloads:/usr/share/scrapyd
    environment:
      TZ: Asia/Shanghai
      SCRAPYD_USERNAME_FILE: /run/secrets/scrapyd_username.txt
      SCRAPYD_PASSWORD_FILE: /run/secrets/scrapyd_password.txt
    secrets:
      - scrapyd_username.txt
      - scrapyd_password.txt
    deploy:
      resources:
        limits:
          memory: 2048M

  gwq5210_scrapydweb:
    image: gwq5210/scrapydweb:latest
    container_name: gwq5210_scrapydweb # 容器名
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./scrapydweb/conf/settings.py:/app/scrapydweb_settings_v10.py
      - ${DOCKER_SITE_LOGS_DIR}/scrapyd:/var/log/scrapyd
      - ${DOCKER_SITE_DATA_DIR}/scrapyd:/var/lib/scrapyd
      - ${DOCKER_SITE_DATA_DIR}/scrapydweb:/app/data
    depends_on:
      - gwq5210_scrapyd
      - gwq5210_mysql
    secrets:
      - scrapyd_username.txt
      - scrapyd_password.txt
      - gwq5210.com.key
      - gwq5210.com.crt
      - mysql_root_password.txt
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 2048M

  gwq5210_elasticsearch:
    image: gwq5210/elasticsearch:latest
    container_name: gwq5210_elasticsearch
    environment:
      - TZ=Asia/Shanghai
      - bootstrap.memory_lock=true
      - xpack.license.self_generated.type=${LICENSE}
      - ELASTIC_PASSWORD_FILE=/run/secrets/elasticsearch_bootstrap_password.txt
      - KEYSTORE_PASSWORD_FILE=/run/secrets/elasticsearch_keystore_password.txt
    secrets:
      - source: gwq5210.com.crt
        target: $ES_CERTS_DIR/gwq5210.com.crt
      - source: gwq5210.com.key
        target: $ES_CERTS_DIR/gwq5210.com.key
      - source: ca.crt
        target: $ES_CERTS_DIR/ca.crt
      - source: elasticsearch_bootstrap_password.txt
        target: /run/secrets/elasticsearch_bootstrap_password.txt
        mode: 400
      - source: elasticsearch_keystore_password.txt
        target: /run/secrets/elasticsearch_keystore_password.txt
        mode: 400
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${DOCKER_SITE_BACKUP_DIR}/elasticsearch:/usr/share/elasticsearch/backup
      - ${DOCKER_SITE_KEY_DATA_DIR}/elasticsearch/data:/usr/share/elasticsearch/data
      - ${DOCKER_SITE_KEY_DATA_DIR}/elasticsearch/config/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
      - ./elasticsearch/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    deploy:
      resources:
        limits:
          memory: 2048M

  gwq5210_kibana:
    image: gwq5210/kibana:latest
    container_name: gwq5210_kibana
    depends_on:
      - gwq5210_elasticsearch
    ports:
      - 5601:5601
    environment:
      TZ: Asia/Shanghai
    secrets:
      - source: gwq5210.com.crt
        target: $KIBANA_CERTS_DIR/gwq5210.com.crt
      - source: gwq5210.com.key
        target: $KIBANA_CERTS_DIR/gwq5210.com.key
      - source: ca.crt
        target: $KIBANA_CERTS_DIR/ca.crt
    volumes:
      - ./kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/conf/node.options:/usr/share/kibana/config/node.options
      - ${DOCKER_SITE_KEY_DATA_DIR}/kibana/config/kibana.keystore:/usr/share/kibana/config/kibana.keystore
    deploy:
      resources:
        limits:
          memory: 2048M

  gwq5210_napcat:
    secrets:
      - napcat_webui_token.txt
    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
      - NAPCAT_WEBUI_TOKEN_FILE=/run/secrets/napcat_webui_token.txt
    volumes:
      - ${DOCKER_SITE_CONF_DIR}/napcat:/app/napcat/config
      - ./napcat/conf/napcat.json:/app/napcat/config/napcat.json
      - ./napcat/conf/onebot11.json:/app/napcat/config/onebot11.json
      - ${DOCKER_SITE_DATA_DIR}/napcat/QQ:/app/.config/QQ
    ports:
      - 3000:3000
      - 3001:3001
      - 6099:6099
    mac_address: "02:42:0a:00:16:01"
    container_name: gwq5210_napcat
    image: gwq5210/napcat:latest
