version: "3.1"

secrets:
  # top level secrets block
  gwq5210.com.key:
    file: secrets/gwq5210.com.key
  gwq5210.com.crt:
    file: secrets/gwq5210.com.crt
  ca.crt:
    file: certs/ca/ca.crt
  mysql_root_password.txt:
    file: secrets/mysql_root_password.txt
  v2ray_uuid.txt:
    file: secrets/v2ray_uuid.txt
  scrapyd_username.txt:
    file: secrets/scrapyd_username.txt
  scrapyd_password.txt:
    file: secrets/scrapyd_password.txt
  elasticsearch_username.txt:
    file: secrets/elasticsearch_username.txt
  elasticsearch_bootstrap_password.txt:
    file: secrets/elasticsearch_bootstrap_password.txt
  elasticsearch_keystore_password.txt:
    file: secrets/elasticsearch_keystore_password.txt
  napcat_webui_token.txt:
    file: secrets/napcat_webui_token.txt
  onebot_qq.txt:
    file: secrets/onebot_qq.txt
  cngzf_sn_code.txt:
    file: secrets/cngzf_sn_code.txt
  idcard.txt:
    file: secrets/idcard.txt
  qq_notify_recipients.json:
    file: secrets/qq_notify_recipients.json

services:
  gwq5210_nginx:
    image: gwq5210/nginx:latest
    container_name: gwq5210_nginx
    secrets:
      - gwq5210.com.key
      - gwq5210.com.crt
    volumes:
      - ./nginx/usconf/conf.d:/etc/nginx/conf.d
      - ./nginx/usconf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/var/www/gwq5210.com/html
      - ${DOCKER_SITE_LOGS_DIR}/nginx:/var/log/nginx
    ports:
      # host模式这个配置失效
      - "80:80"
      - "443:443"
      - "9445:9445"
      - "9447:9447"
      - "19443:19443"
      - "19445:19445"
      - "19447:19447"
      - "19449:19449"
      - "22333:22333"
    depends_on:
      - gwq5210_v2ray
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      TZ: Asia/Shanghai
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2048M

  gwq5210_v2ray:
    image: gwq5210/v2ray:latest
    container_name: gwq5210_v2ray # 容器名
    secrets:
      - v2ray_uuid.txt
    volumes:
      - ./v2ray/conf/config.json:/etc/v2ray/config.json
      - ${DOCKER_SITE_LOGS_DIR}/v2ray:/var/log/v2ray
    environment:
      TZ: Asia/Shanghai
      V2RAY_UUID_FILE: /run/secrets/v2ray_uuid.txt
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2048M