version: "3.1"

services:
  portainer:
    container_name: portainer
    image: gwq5210/portainer:latest
    command: -H unix:///var/run/docker.sock --tlsskipverify --sslcert /run/secrets/gwq5210.com.crt --sslkey /run/secrets/gwq5210.com.key --secret-key-name="portainer_key.txt"
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_SITE_KEY_DATA_DIR}/portainer/data:/data
      - ${DOCKER_SITE_HOME}:/home
    deploy:
      resources:
        limits:
          memory: 2048M
    secrets:
      - gwq5210.com.crt
      - gwq5210.com.key
      - portainer_key.txt
    environment:
      TZ: Asia/Shanghai

  portainer_backup:
    container_name: portainer_backup
    image: gwq5210/portainer_backup:latest
    hostname: portainer-backup
    restart: unless-stopped
    command: schedule --filename "portainer-backup-{{DATETIME}}.tar.gz"
    depends_on:
      - portainer
    environment:
      TZ: Asia/Shanghai
      PORTAINER_BACKUP_URL: "https://gwq5210.com:9443"
      PORTAINER_BACKUP_TOKEN_FILE: "/run/secrets/portainer_token.txt"
      PORTAINER_BACKUP_PASSWORD_FILE: "/run/secrets/portainer_backup_password.txt"
      PORTAINER_BACKUP_OVERWRITE: 1
      PORTAINER_BACKUP_SCHEDULE: "0 0 2 * * *"
      PORTAINER_BACKUP_STACKS: 1
      PORTAINER_BACKUP_DRYRUN: 0
      PORTAINER_BACKUP_CONCISE: 0
      PORTAINER_BACKUP_DIRECTORY: "/backup"
      PORTAINER_BACKUP_DEBUG: 0
    volumes:
      - ${DOCKER_SITE_BACKUP_DIR}/portainer:/backup
    deploy:
      resources:
        limits:
          memory: 2048M
    secrets:
      - portainer_token.txt
      - portainer_backup_password.txt

secrets:
  gwq5210.com.crt:
    file: secrets/gwq5210.com.crt
  gwq5210.com.key:
    file: secrets/gwq5210.com.key
  portainer_token.txt:
    file: secrets/portainer_token.txt
  portainer_backup_password.txt:
    file: secrets/portainer_backup_password.txt
  portainer_key.txt:
    file: secrets/portainer_key.txt
