version: "3.1"
secrets:                        # top level secrets block
  elasticsearch_bootstrap_password.txt:
    file: secrets/elasticsearch_bootstrap_password.txt
  elasticsearch_keystore_password.txt:
    file: secrets/elasticsearch_keystore_password.txt
  elasticsearch_username.txt:
    file: secrets/elasticsearch_username.txt

services:
  setup_elasticsearch_keystore:
    image: gwq5210/elasticsearch:latest
    environment:
      - TZ=Asia/Shanghai
      - ELASTIC_PASSWORD_FILE=/run/secrets/elasticsearch_bootstrap_password.txt
      - KEYSTORE_PASSWORD_FILE=/run/secrets/elasticsearch_keystore_password.txt
    volumes:
      - ${DOCKER_SITE_KEY_DATA_DIR}/elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/setup_keystore.sh:/usr/share/elasticsearch/setup_keystore.sh
    working_dir: /usr/share/elasticsearch
    command:
      - /bin/sh
      - -c
      - |
        sh setup_keystore.sh
    secrets:
      - source: elasticsearch_bootstrap_password.txt
        target: /run/secrets/elasticsearch_bootstrap_password.txt
        mode: 0400
      - source: elasticsearch_keystore_password.txt
        target: /run/secrets/elasticsearch_keystore_password.txt
        mode: 0400
    deploy:
      restart_policy:
        condition: none

  setup_kibana_keystore:
    image: gwq5210/kibana:latest
    container_name: setup_kibana_keystore
    environment:
      TZ: Asia/Shanghai
      ELASTICSEARCH_USERNAME_FILE: '/run/secrets/elasticsearch_username.txt'
      ELASTICSEARCH_PASSWORD_FILE: '/run/secrets/elasticsearch_bootstrap_password.txt'
    volumes:
      - ${DOCKER_SITE_KEY_DATA_DIR}/kibana/config:/usr/share/kibana/config
      - ./kibana/setup_keystore.sh:/usr/share/kibana/setup_keystore.sh
    working_dir: /usr/share/kibana
    command:
      - /bin/sh
      - -c
      - |
        sh setup_keystore.sh
    secrets:
      - elasticsearch_username.txt
      - elasticsearch_bootstrap_password.txt
    deploy:
      restart_policy:
        condition: none