version: "3.1"
secrets:                        # top level secrets block
  elasticsearch_bootstrap_password.txt:
    file: elasticsearch/elasticsearch_bootstrap_password.txt
  elasticsearch_keystore_password.txt:
    file: elasticsearch/elasticsearch_keystore_password.txt
  elasticsearch_username.txt:
    file: elasticsearch/elasticsearch_username.txt

services:
  setup_certs:
    # image: gwq5210/elasticsearch:latest
    build:
      context: .
      dockerfile: ./elasticsearch/Dockerfile
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch/setup_certs.sh:/usr/share/elasticsearch/setup_certs.sh
    working_dir: /usr/share/elasticsearch
    command:
      - /bin/sh
      - -c
      - |
        sh setup_certs.sh

  setup_elasticsearch_keystore:
    # image: gwq5210/elasticsearch:latest
    build:
      context: .
      dockerfile: ./elasticsearch/Dockerfile
    environment:
      - TZ=Asia/Shanghai
      - ELASTIC_PASSWORD_FILE=/run/secrets/elasticsearch_bootstrap_password.txt
      - KEYSTORE_PASSWORD_FILE=/run/secrets/elasticsearch_keystore_password.txt
    volumes:
      - ${DOCKER_SITE_KEY_DATA_DIR}/elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/setup_keystore.sh:/usr/share/elasticsearch/setup_keystore.sh
    working_dir: /usr/share/elasticsearch
    command:
      - /bin/sh
      - -c
      - |
        sh setup_keystore.sh
    secrets:
      - elasticsearch_bootstrap_password.txt
      - elasticsearch_keystore_password.txt

  setup_kibana_keystore:
    # image: gwq5210/kibana
    build:
      context: .
      dockerfile: ./kibana/Dockerfile
    container_name: setup_kibana_keystore
    environment:
      TZ: Asia/Shanghai
      ELASTICSEARCH_USERNAME_FILE: '/run/secrets/elasticsearch_username.txt'
      ELASTICSEARCH_PASSWORD_FILE: '/run/secrets/elasticsearch_bootstrap_password.txt'
    volumes:
      - ${DOCKER_SITE_KEY_DATA_DIR}/kibana/config:/usr/share/kibana/config
      - ./kibana/setup_keystore.sh:/usr/share/kibana/setup_keystore.sh
    working_dir: /usr/share/kibana
    command:
      - /bin/sh
      - -c
      - |
        sh setup_keystore.sh
    secrets:
      - elasticsearch_username.txt
      - elasticsearch_bootstrap_password.txt